# Generated by Django 5.2.8 on 2025-11-17 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lessons", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons_as_student",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Студент",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="teacher",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "teacher"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons_as_teacher",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Преподаватель",
            ),
        ),
    ]
